# Generated by Django 4.2.19 on 2025-04-30 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together={("user", "event")},
        ),
        migrations.AddField(
            model_name="participation",
            name="is_coming",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
